# Generated by Django 5.2.3 on 2025-06-20 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_updates', models.BooleanField(default=False)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_subscribed'],
            },
        ),
        migrations.CreateModel(
            name='Quickcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='listings/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('kitchen', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default='draft', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agents.agent')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['id', 'slug'], name='shelter_lis_id_498e5d_idx')],
            },
        ),
    ]
