# Generated by Django 5.2.3 on 2025-06-20 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('related_customer_id', models.IntegerField(blank=True, help_text='Related customer ID if applicable', null=True)),
                ('related_property_id', models.IntegerField(blank=True, help_text='Related property ID if applicable', null=True)),
                ('related_lead_id', models.IntegerField(blank=True, help_text='Related lead ID if applicable', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Note',
                'verbose_name_plural': 'Work Notes',
                'ordering': ['-date_created'],
            },
        ),
    ]
