# Generated by Django 5.2.3 on 2025-06-20 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('member', 'Team Member'), ('manager', 'Manager'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('lead', 'Team Lead')], default='member', help_text='Role of the team member in organization', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to user account if team member has system access', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
