# Generated by Django 5.2.3 on 2025-06-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teamrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
